apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed
  labels:
    app: feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      restartPolicy: Always
      containers:
      - name: udacity-ch3-feed
        image: samcowley/udacity-ch3-feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "1024Mi"
            cpu: "512m"
        env:
        - name: NODE_OPTIONS
          value: "--max-old-space-size=8192"
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: config
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: config
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: BACKEND_URL
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret
