apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: udacity-ch3-frontend
        image: samcowley/udacity-ch3-frontend
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        ports:
        - containerPort: 80
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: config
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: config
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: config
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: config
              key: AWS_PROFILE
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secrets
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: config
              key: FRONTEND_URL
