apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  ports:
  - name: http
    port: 8100
    targetPort: 8100
  selector:
    service: frontend
  type: LoadBalancer
